spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoice_database?serverTimezone=UTC
    username: root
    password: hesloveslo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  port: 8080
springdoc:
  api-docs.path: /api-docs